# IDENTITY
spring:
  application:
    name: learning-spring-webmvc

  # JACSON  
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
      write-dates-as-timestamps: false

  # H2 Web Console (H2ConsoleProperties)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    continue-on-error: true
    url: jdbc:h2:~/webmvc;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true

# LOGGING
logging:
  level:
    root: info
    me.learning: debug
    org.springframework: info
    com.zaxxer: trace

# Integration Properties
integration:
  enabled: true
  servers:
    - name: dev-server1
      base-url: 10.0.0.1
      description: DEV SERVER1
    - name: dev-server2
      base-url: 10.0.0.2
      description: DEV SERVER2



