# IDENTITY
spring:
  application:
    name: learning-spring-webmvc
  
  # JACSON  
  jackson:
    default-property-inclusion: non-null
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      
  # H2 Web Console (H2ConsoleProperties)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        
  # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    continue-on-error: true
    url: jdbc:h2:~/webmvc
    username: sa
    password: 
    driver-class-name: org.h2.Driver
      
  # JPA (JpaBaseConfiguration, HibernateJpaAutoConfiguration)
  jpa:
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create-drop
    properties:
      hibernate.format_sql: true

# LOGGING
logging:
  level:
    root: info
    me.learning: debug
    org.springframework: info
    com.zaxxer: trace